@echo off
echo Syncing NekoTrans to GitHub...
echo 1. Adding changes...
git add .
echo 2. Committing changes...
git commit -m "Sync: %date% %time%"
echo 3. Pushing to main branch...
git push origin main
echo Sync complete!
pause
